# Generated by Django 3.2.8 on 2022-04-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curlyguardian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curlyguardian',
            name='other_individual_curl_type',
        ),
        migrations.RemoveField(
            model_name='curlyguardian',
            name='other_individual_name',
        ),
    ]
