# Generated by Django 3.2.8 on 2022-04-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curlycrew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curlycrew',
            name='self_or_other',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
