# Generated by Django 3.2.8 on 2022-04-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairvideos', '0004_rename_faveorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
    ]
